apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres
resources:
- serviceaccounts.yaml
- secrets.yaml
- clusterroles.yaml
- clusterrolebindings.yaml
- roles.yaml
- rolebindings.yaml
- services.yaml
- deployments.yaml
- validatingwebhookconfigurations.yaml
