apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-ldap-setup-tasks
  namespace: keycloak
data:
  main.yaml: |
    ---

    - name: Configure keycloak realm
      community.general.keycloak_realm:
        validate_certs: false
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ AUTH_URL }}"
        auth_realm: master
        auth_username: "{{ AUTH_ADMIN_USERNAME }}"
        auth_password: "{{ AUTH_ADMIN_PASSWORD }}"
        state: present
        id: "{{ AUTH_REALM }}"
        realm: "{{ AUTH_REALM }}"
        enabled: true
        displayName: "{{ AUTH_REALM }}"
        registrationAllowed: false
        resetPasswordAllowed: false
        editUsernameAllowed: false
        internationalizationEnabled: false
        rememberMe: false
        verifyEmail: true
        loginWithEmailAllowed: false
        accessTokenLifespan: 1800
        ssoSessionIdleTimeout: 1800

    - name: Configure authentication browser executions
      community.general.keycloak_authentication:
        validate_certs: false
        auth_keycloak_url: "{{ AUTH_URL }}"
        auth_realm: master
        auth_username: "{{ AUTH_ADMIN_USERNAME }}"
        auth_password: "{{ AUTH_ADMIN_PASSWORD }}"
        realm: "{{ AUTH_REALM }}"
        state: present
        force: true
        alias: CILogon First Broker Login
        copyFrom: "first broker login"
        authenticationExecutions:
          - providerId: identity-provider-redirector
            requirement: REQUIRED
            index: 4
            authenticationConfig:
              alias: openshift
              config:
                defaultProvider: openshift
      ignore_errors: true

    - name: Configure Keycloak CI Logon identity provider
      community.general.keycloak_identity_provider:
        state: present
        validate_certs: false
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ AUTH_URL }}"
        auth_realm: master
        auth_username: "{{ AUTH_ADMIN_USERNAME }}"
        auth_password: "{{ AUTH_ADMIN_PASSWORD }}"
        enabled: true
        realm: "{{ AUTH_REALM }}"
        providerId: oidc
        alias: cilogon
        displayName: cilogon
        config:
          fromUrl: https://cilogon.org/.well-known/openid-configuration
          clientId: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='cilogon-identity-provider', namespace=AUTH_NAMESPACE)[0].data['CILOGON_CLIENT'] | b64decode }}"
          clientSecret: "{{ query('kubernetes.core.k8s', kind='Secret', resource_name='cilogon-identity-provider', namespace=AUTH_NAMESPACE)[0].data['CILOGON_SECRET'] | b64decode }}"
          clientAuthMethod: "client_secret_post"
          acceptsPromptNoneForwardFromClient: false
          isAccessTokenJWT: false
          claimFilterValue: (?i)^[^@\\s]+@(domain1\\.edu|domain2\\.edu|domain3\\.org)$
          showInAccountConsole: ALWAYS
          filteredByClaim: true
          jwtAuthorizationGrantEnabled: false
          backchannelSupported: false
          caseSensitiveOriginalUsername: false
          loginHint: false
          syncMode: IMPORT
          supportsClientAssertions: false
          requiresShortStateParameter: false
          allowedClockSkew: 0
          validateSignature: false
          uiLocales: false
          disableNonce: false
          sendClientIdOnLogout: false
          pkceEnabled: false
          claimFilterName: email
          disableUserInfo: false
          sendIdTokenOnLogout: true
          passMaxAge: false
          disableTypeClaimCheck: false

    - name: "Configure keycloak client scope openid"
      community.general.keycloak_clientscope:
        validate_certs: false
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ AUTH_URL }}"
        auth_realm: master
        auth_username: "{{ AUTH_ADMIN_USERNAME }}"
        auth_password: "{{ AUTH_ADMIN_PASSWORD }}"
        state: present
        id: "{{ AUTH_REALM }}-openid"
        realm: "{{ AUTH_REALM }}"
        name: "openid"
        description: A client scope for the openid client
        protocol: openid-connect
        attributes:
          include.in.token.scope: 'true'
        protocolMappers:
          - config:
              access.token.claim: 'true'
              introspection.token.claim: 'true'
            id: "{{ AUTH_REALM }}-openid-sub"
            name: "sub"
            protocol: openid-connect
            protocolMapper: oidc-sub-mapper

    - name: "Configure keycloak client scope {{ AUTH_CLIENT }}"
      community.general.keycloak_clientscope:
        validate_certs: false
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ AUTH_URL }}"
        auth_realm: master
        auth_username: "{{ AUTH_ADMIN_USERNAME }}"
        auth_password: "{{ AUTH_ADMIN_PASSWORD }}"
        state: present
        id: "{{ AUTH_REALM }}-{{ AUTH_CLIENT }}"
        realm: "{{ AUTH_REALM }}"
        name: "{{ AUTH_CLIENT }}"
        description: A client scope for the {{ AUTH_CLIENT }} client
        protocol: openid-connect
        attributes:
          include.in.token.scope: 'true'
        protocolMappers:
          - config:
              access.token.claim: 'true'
              id.token.claim: 'false'
              included.client.audience: '{{ AUTH_CLIENT }}'
            id: "{{ AUTH_REALM }}-{{ AUTH_CLIENT }}"
            name: "{{ AUTH_CLIENT }}"
            protocol: openid-connect
            protocolMapper: oidc-audience-mapper
          - config:
              full.path: "true"
              introspection.token.claim: "true"
              userinfo.token.claim: "true"
              id.token.claim: "true"
              lightweight.claim: "false"
              access.token.claim: "true"
              claim.name: "groups"
            id: "{{ AUTH_REALM }}-{{ AUTH_CLIENT }}-groups"
            name: "groups"
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper

    - name: "Disable RSA-OAEP key component from {{ AUTH_REALM }}"
      community.general.keycloak_component:
        validate_certs: false
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ AUTH_URL }}"
        auth_realm: master
        auth_username: "{{ AUTH_ADMIN_USERNAME }}"
        auth_password: "{{ AUTH_ADMIN_PASSWORD }}"
        state: absent
        name: rsa-enc-generated
        parent_id: "{{ AUTH_REALM }}"
        provider_id: rsa-enc-generated
        provider_type: org.keycloak.keys.KeyProvider

    - name: "Configure OpenShift client {{ AUTH_CLIENT }}"
      community.general.keycloak_client:
        state: present
        validate_certs: false
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ AUTH_URL }}"
        auth_realm: master
        auth_username: "{{ AUTH_ADMIN_USERNAME }}"
        auth_password: "{{ AUTH_ADMIN_PASSWORD }}"
        realm: "{{ AUTH_REALM }}"
        id: "{{ AUTH_CLIENT }}"
        name: "{{ AUTH_CLIENT }}"
        clientId: "{{ AUTH_CLIENT }}"
        standardFlowEnabled: true
        serviceAccountsEnabled: true
        authorizationServicesEnabled: true
        frontchannelLogout: true
        publicClient: false
        protocol: openid-connect
        redirectUris: []
        defaultClientScopes:
          - openid
          - profile
          - "{{ AUTH_CLIENT }}"
        authorizationSettings:
          decisionStrategy: AFFIRMATIVE

    - name: Get a new Keycloak client secret, passing client_id instead of id
      community.general.keycloak_clientsecret_info:
        validate_certs: false
        auth_client_id: admin-cli
        auth_keycloak_url: "{{ AUTH_URL }}"
        auth_realm: master
        auth_username: "{{ AUTH_ADMIN_USERNAME }}"
        auth_password: "{{ AUTH_ADMIN_PASSWORD }}"
        client_id: '{{ AUTH_CLIENT }}'
        realm: "{{ AUTH_REALM }}"
      register: AUTH_CLIENT_SECRET
    - name: Set AUTH_SECRET variable
      set_fact:
        AUTH_SECRET: "{{ AUTH_CLIENT_SECRET.clientsecret_info.value }}"
